services:
  www:
    depends_on:
      - db
    build:
      context: ./docker/php
    volumes:
    - "./src:/var/www/html"
    ports:
    - 8000:80
    networks:
      - xwebapp-network

  xwaff:
    container_name: xwaff
    build:
      context: ./waf
    volumes:
    - "./waf:/xwaff"
    ports:
    - 5000:5000
    networks:
      - xwebapp-network

  db:
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=xwebapp
      - MARIADB_USER=xwebapp
      - MARIADB_PASSWORD=@Y01z)2mmPU
      - MARIADB_ROOT_PASSWORD={12'x*P45500
    networks:
      - xwebapp-network
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

networks:
  xwebapp-network:
    driver: bridge